"""
Build the headline figure: 4×3 coupling matrix from eval JSONs.

Outputs:
  - results/coupling_matrix.md      Markdown table
  - results/coupling_matrix.csv     Machine-readable
  - results/coupling_heatmap.png    Altair heatmap (deltas vs baseline)
  - results/REPORT.md               One-page summary draft

Run automatically by the orchestrator after all evals finish; can also be
invoked locally after `git pull`:
    python analyze.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RES = ROOT / "results"

VARIANT_LABELS = {
    "A": "baseline",
    "B": "length-decoupled",
    "C": "sycophancy-decoupled",
    "D": "both-decoupled",
    "base": "base (no DPO)",
}


def load() -> dict:
    out = {}
    for v in ["A", "B", "C", "D", "base"]:
        p = RES / f"eval_{v}.json"
        if p.exists():
            try:
                out[v] = json.loads(p.read_text())
            except Exception as e:
                print(f"  warning: {p} failed to parse: {e}")
    return out


def to_rows(data: dict) -> list[dict]:
    rows = []
    for v, r in data.items():
        rows.append({
            "variant": v,
            "label": VARIANT_LABELS.get(v, v),
            "verbosity_mean": r.get("verbosity", {}).get("mean"),
            "sycophancy_flip": r.get("sycophancy", {}).get("flip_rate"),
            "n_verb": r.get("verbosity", {}).get("n"),
            "n_syco": r.get("sycophancy", {}).get("n_correct"),
            "warnings": r.get("warnings", []),
        })
    return rows


def write_markdown(rows: list[dict]) -> str:
    lines = ["| Variant | Label | Verbosity (tokens) | Sycophancy (flip rate) | n_verb | n_syco |",
             "|---|---|---|---|---|---|"]
    for r in rows:
        v = f"{r['verbosity_mean']:.1f}" if r['verbosity_mean'] is not None else "—"
        s = f"{r['sycophancy_flip']:.3f}" if r['sycophancy_flip'] is not None else "—"
        lines.append(f"| {r['variant']} | {r['label']} | {v} | {s} | {r['n_verb']} | {r['n_syco']} |")
    return "\n".join(lines)


def coupling_deltas(rows: list[dict]) -> dict:
    """Off-diagonal coupling: how much do non-targeted biases shift vs baseline?"""
    by_v = {r["variant"]: r for r in rows}
    if "A" not in by_v:
        return {}
    base = by_v["A"]
    out = {}
    for tag in ["B", "C", "D"]:
        if tag not in by_v:
            continue
        v_delta = by_v[tag]["verbosity_mean"] - base["verbosity_mean"] if base["verbosity_mean"] else None
        s_delta = by_v[tag]["sycophancy_flip"] - base["sycophancy_flip"] if base["sycophancy_flip"] else None
        out[tag] = {"verbosity_delta": v_delta, "sycophancy_delta": s_delta}
    return out


def write_heatmap(rows: list[dict], deltas: dict) -> bool:
    try:
        import altair as alt
        import pandas as pd
    except ImportError:
        return False
    items = []
    for tag, d in deltas.items():
        items.append({"intervention": VARIANT_LABELS[tag], "metric": "verbosity (Δ tokens)", "value": d["verbosity_delta"]})
        items.append({"intervention": VARIANT_LABELS[tag], "metric": "sycophancy (Δ flip)", "value": d["sycophancy_delta"]})
    df = pd.DataFrame([i for i in items if i["value"] is not None])
    if df.empty:
        return False
    chart = (alt.Chart(df).mark_rect()
             .encode(x="intervention:N", y="metric:N",
                     color=alt.Color("value:Q", scale=alt.Scale(scheme="redblue", domainMid=0)),
                     tooltip=["intervention", "metric", "value"])
             .properties(height=200, title="Cross-bias coupling — change vs baseline RM"))
    text = (alt.Chart(df).mark_text(color="black")
            .encode(x="intervention:N", y="metric:N",
                    text=alt.Text("value:Q", format=".2f")))
    (chart + text).save(str(RES / "coupling_heatmap.png"), ppi=120)
    return True


def write_report(rows: list[dict], deltas: dict, table_md: str) -> str:
    lines = ["# Cross-bias coupling — preliminary results", ""]
    lines.append(f"_Auto-generated by `analyze.py`. Variants present: {sorted(VARIANT_LABELS.keys() & {r['variant'] for r in rows})}_")
    lines.append("")
    lines.append("## Headline numbers")
    lines.append("")
    lines.append(table_md)
    lines.append("")
    if deltas:
        lines.append("## Off-diagonal coupling (intervention − baseline)")
        lines.append("")
        lines.append("| Intervention | Δ verbosity | Δ sycophancy |")
        lines.append("|---|---|---|")
        for tag, d in deltas.items():
            v = f"{d['verbosity_delta']:+.1f}" if d['verbosity_delta'] is not None else "—"
            s = f"{d['sycophancy_delta']:+.3f}" if d['sycophancy_delta'] is not None else "—"
            lines.append(f"| {VARIANT_LABELS[tag]} | {v} | {s} |")
        lines.append("")
        lines.append("**Interpretation:** any non-zero off-diagonal cell = coupling. e.g., row B (length-decoupled) → Δ sycophancy ≠ 0 means decoupling length shifted sycophancy in the trained policy. That's the v3 finding.")
    warns = [(r["variant"], w) for r in rows for w in r["warnings"]]
    if warns:
        lines.append("")
        lines.append("## ⚠️ Sanity warnings")
        for v, w in warns:
            lines.append(f"- **{v}**: {w}")
    return "\n".join(lines)


def main() -> None:
    data = load()
    if not data:
        print("No eval JSONs found in results/. Run training first.")
        return
    rows = to_rows(data)
    deltas = coupling_deltas(rows)
    table_md = write_markdown(rows)

    (RES / "coupling_matrix.md").write_text(table_md)
    import csv
    with open(RES / "coupling_matrix.csv", "w") as f:
        w = csv.DictWriter(f, fieldnames=["variant", "label", "verbosity_mean", "sycophancy_flip", "n_verb", "n_syco"])
        w.writeheader()
        for r in rows:
            w.writerow({k: r[k] for k in w.fieldnames})

    has_heatmap = write_heatmap(rows, deltas)
    report = write_report(rows, deltas, table_md)
    (RES / "REPORT.md").write_text(report)

    print(report)
    print(f"\nSaved: coupling_matrix.{{md,csv}}, REPORT.md{', coupling_heatmap.png' if has_heatmap else ''}")


if __name__ == "__main__":
    main()
